---
- name: ensure {{ dc_dest_dir }} is present
  file:
    path: '{{ dc_dest_dir }}'
    state: directory
    mode: 0755

- name: ensure {{ dc_compose_file_dest }} is placed
  copy:
    src: '{{ dc_compose_file_src }}'
    dest: '{{ dc_compose_file_dest }}'
    validate: '{{ dc_compose_bin }} -f %s config -q'

# ensure newer image with latest tag will be pulled
- name: pull images
  shell: '{{ dc_compose_bin }} -f {{ dc_compose_file_dest }} pull'

- name: deploy containers
  shell: '{{ dc_compose_bin }} -f {{ dc_compose_file_dest }} up -d'
